name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: "${{matrix.os}}-latest"

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 22
          - 24
          - 26
        os: 
          - ubuntu
          - windows

    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/action-setup@v6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: pnpm
    - run: pnpm install
    - run: pnpm test
